In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("data.csv")

df.tail(5)

In [ ]:
df.describe()

In [ ]:
df.dtypes

In [ ]:
## Handling missing values

df.isnull().any(axis=1)

In [ ]:
df.isnull().sum()

In [ ]:
filled = df.fillna(0)

In [ ]:
## Filling missing values with mean
df['Sales_fillna']=df['Sales'].fillna(df['Sales'].mean())
df

In [ ]:
## Renaming Columns

df = df.rename(columns={"Date":"Sales_date"})
df.head(5)

In [ ]:
## change datatypes
df['Value_new']=df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

In [ ]:
df['New Value']=df['Value'].apply(lambda x:x*2)
df.head()

In [27]:
## Data Aggregating And Grouping
df.head()

,Sales_date,Category,Value,Product,Sales,Region,Sales_fillna,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

In [28]:
grouped_mean = df.groupby('Product')['Value'].mean()
grouped_mean

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [ ]:
sum = df.groupby(['Product','Region'])['Value'].sum()
sum

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [30]:
mean = df.groupby(['Product','Region'])['Value'].mean()
mean

Product   Region
Product1  East      41.714286
          North      4.500000
          South     50.000000
          West      82.000000
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     40.600000
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [31]:
## Aggregate multiple functions

groudped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
groudped_agg

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

In [33]:
### Merging and joining Dataframes
# Create sample DataFrames
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [34]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [35]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [40]:
pd.merge(df1,df2,on="Key",how="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [42]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [43]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [44]:
pd.merge(df1,df2,on="Key",how='right')

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6